# file 是文件目录 e.g. /C/a.txt
# sheetBook 是excel中的工作薄 e.g. Sheet1
# 注意file和sheetBook一定要对上！！！！！！！！！！不知道sheetBook是什么请打开excel看
# 注意文件名一定不能是中文，中间不能出现空格 ！！！！
excel1:
  file: "./excel/缺.xlsx"
  sheetBook: "Sheet1"

excel2:
  file: "./excel/困难户名单.xlsx"
  sheetBook: "缺"
